# Generated by Django 6.0.3 on 2026-04-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_issuebook_is_returned_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='total_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
