# Generated by Django 6.0.3 on 2026-04-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_book_available_quantity_book_total_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='due_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='issuebook',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
