# Generated by Django 6.0.3 on 2026-04-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_number',
            field=models.IntegerField(choices=[(6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=6),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('class_number', 'section', 'roll_no')},
        ),
    ]
